services:
  mongo:
    image: mongo:6.0.4
    container_name: star-wars-api.mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
