services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: star-wars-api.test
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - "${HOST_APP_DATA_DIR:-./app-data}/star-wars-api/reports:/home/gradle/project/reports"
